// const engLang = {
    // changeLangBtn: 'Change language (язык)',
    // myRatings: 'My ratings',
    // loginBtn: 'Login/Register',
    // addEvaluation: 'Add new rating',
    // logoutBtn: 'Log out',
    // rate__rated_btn: 'You have already rated this place',
    // openLoginFromRatings: `Login and rate`,

    // ratingText1: 'So you want to rate the place. Before we start, there is one important question to answer. We expect a honest answer, thank you!',
    // ratingText2: 'Do you have personal experience of living at the given place?',
    // ratingText3: `Great, thanks. There are about ten criterias you will need to rate in order to submit your rating. You can skip and return later, there is an opportunity to leave a comment at the end. Let's start with <strong class="rating__text-highlight">important</strong>:`,
    // ratingText4: 'Location',
    // ratingText5: 'Comfort',
    // ratingText6: 'Extras',
    // ratingText7: 'Comment',
    // ratingText8: `Anything you'd like to add?`,
    // ratingText9: `We <a href="policy" class="rating__link">fight</a> dishonesty around here.`,

    // btnPersExp: 'Yes, I lived here',
    // ratingBtn1: `No, I don't`,
    // ratingBtn2: 'Back',
    // ratingBtn3: 'Next',
    // ratingBtn4: 'Save',

    // ratingTitle1: 'Air quality',
    // ratingTitle2: 'Water quality',
    // ratingTitle3: 'Level of communication and logistics',
    // ratingTitle4: 'Transport and location conditions',
    // ratingTitle5: 'Light and noise pollution',
    // ratingTitle6: 'Cleanliness',
    // ratingTitle7: 'Places for rest',
    // ratingTitle8: 'Safety',
    // ratingTitle9: 'Life with pets',
    // ratingTitle10: 'Life with kids',
    // ratingTitle11: 'Parking places',

    // comments__title: 'Comments',
    // settings__title: 'Settings',
    // spinner__text: 'Loading',
    // error_screen__text: 'Unfortunately, there is no response from the server. Try later or contact us: support@measureland.org',

    // rateText1: 'Av. rating: ',
    // rateText2: 'Users rated: ',
    // rateText3: 'Comments',

    // loginText1: 'Log in',
    // loginText2: 'Email',
    // loginText3: 'Password',
    // loginText4: 'Show/hide',
    // loginText5: 'Forgot password',
    // loginText6: 'I want to register!',
    // loginText7: 'Registration',
    // loginText8: 'Repeat the password',
    // loginText9: 'Go to Login',
    // loginText10: 'Restore (change) the password',
    // loginText11: 'Register',
    // loginText12: 'Restore',

    // formText1: 'Wrong email format! Example: yournick@mail.com',
    // formText2: 'Password should be longer than 6 characters',
    // formText3: 'Passwords should match',
    // formText4: `Couldn't find your account`,
    // formText5: 'Wrong password',
    // formText6: 'Error, try again later :(',
    // formText7: 'Check all the fields!',
    // formText8: 'Already verified. Just log in :)',
    // formText9: 'Check email for verification letter',
    // formText10: 'Resend letter',
    // formText11: 'Account already exists',
    // formText12: 'Thank you for registration!',
    // formText13: `You'll help us by answering this two simple questions (or skip it), and we would help you if you were looking for a new place to live in the future :)`,
    // formText14: 'Your age group:',
    // formText15: 'Yonger than 25 years',
    // formText16: '25 - 40 years',
    // formText17: '41 - 55 years',
    // formText18: 'Older than 55 years',
    // formText19: 'Income level (roughly):',
    // formText20: 'Below average',
    // formText21: 'Average',
    // formText22: 'Above average',
    // formText23: `Your name. If skipped, you're going to be "Anonym" in the comments`,
    // formText24: `Let's go`,
    // formText25: 'Check your email',
    // formText26: `One of the stages in fighting with cheating - verification of users by email - so we sent a letter to you. We know you can't wait to start rating the places, so once you confirm yourself you can start. Check it :)`,
    // formText27: 'Go to "Log in"',
    // formText28: 'Password change',
    // formText29: 'Type new password here',
    // formText30: 'The pass is the same as previous. Pick another one.',
    // formText31: 'The link is expired :(',
    // formText32: 'Get another one',
    // formText33: 'Change the password',
    // formText34: `We sent a letter to the given email. By clicking the link inside you'll get to the new password form. Once you submit new password, old one stops to work.`,
    // formText35: 'Got ya',
    // formText36: 'Rate every field please!',
    // formText37: 'Nearby place is already rated',
    // formText38: 'Share this rating',
    // formText39: 'You rate too often, have to wait',
    // formText40: 'Too much attempts, wait a bit',
    // formText41: 'Copied',

    // caption1: `1 - bad, 5 - awesome`,
    // caption2: `1 - terrible, 5 - good`,
    // caption3: `1 - awful, 5 - great`,
    // caption4: `1 - poor, 5 - nice`,
    // caption5: `1 - noizy, 5 - quietly`,
    // caption6: `1 - dirty, 5 - clean`,
    // caption7: `1 - far, 5 - nearby`,
    // caption8: `1 - anxious, 5 - calmly`,
    // caption9: `1 - tough, 5 - easy`,
    // caption10: `1 - rough, 5 - cool`,
    // caption11: `1 - sad, 5 - terrific`,

    // ratingPlaceholder: 'Extremely friendly and clean neighborhood!',
    // searchPlaceholder: 'Search...',
// }

// const rusLang = {
//     changeLangBtn: 'Сменить язык (language)',
//     myRatings: 'Мои оценки',
//     loginBtn: 'Войти/Зарегистрироваться',
//     addEvaluation: 'Добавить свою оценку',
//     logoutBtn: 'Выйти из профиля',
//     rate__rated_btn: 'Твоя оценка уже добавлена',
//     openLoginFromRatings: `Войти и добавить оценку`,
//
//     ratingText1: 'Привет! Итак, ты собираешься оценить место. Мы стараемся сделать оценки как можно более достоверными, поэтому, пожалуйста, ответь сначала на небольшой вопрос. Но помни - всё тайное когда-нибудь становиться явным!',
//     ratingText2: 'Имеешь ли ты опыт проживания в данной местности или собираешься оценивать основываясь на опыте других людей?',
//     ratingText3: `Отлично, спасибо. Вот небольшой список критериев (около 10), а в конце можно будет оставить общий комментарий. Можно пропускать и возвращаться, но оценить нужно все пункты. Начнём с <strong class="rating__text-highlight">важного</strong>:`,
//     ratingText4: 'Расположение',
//     ratingText5: 'Удобство',
//     ratingText6: 'Дополнительно',
//     ratingText7: 'Комментарий',
//     ratingText8: `Есть ли что-то, что бы хотелось добавить?`,
//     ratingText9: `Мы <a href="policy" class="rating__link">гоняем</a> гадких и нечестных накрутчиков и дебоширов!`,
//
//     btnPersExp: 'Имею',
//     ratingBtn1: `Не имею, чужой опыт`,
//     ratingBtn2: 'Вернуться',
//     ratingBtn3: 'Далее',
//     ratingBtn4: 'Сохранить',
//
//     ratingTitle1: 'Качество воздуха',
//     ratingTitle2: 'Качество воды',
//     ratingTitle3: 'Уровень коммуникации и логистики',
//     ratingTitle4: 'Транспортное сообщение и расположение',
//     ratingTitle5: 'Свето- и шумо-загрязнения',
//     ratingTitle6: 'Чистота',
//     ratingTitle7: 'Места для отдыха',
//     ratingTitle8: 'Безопасность',
//     ratingTitle9: 'Жизнь с домашними животными',
//     ratingTitle10: 'Жизнь с детьми',
//     ratingTitle11: 'Места для парковки',
//
//     comments__title: 'Комментарии',
//     settings__title: 'Настройки',
//     spinner__text: 'Загружаем',
//     error_screen__text: 'К сожалению, похоже что сервер не работает. Попробуй позже или пиши: support@measureland.org',
//
//     rateText1: 'Ср. рейтинг: ',
//     rateText2: 'Кол-во оценивших: ',
//     rateText3: 'Комментарии',
//
//     loginText1: 'Войти',
//     loginText2: 'Почта (Email)',
//     loginText3: 'Пароль',
//     loginText4: 'Показать/скрыть',
//     loginText5: 'Не помню пароль',
//     loginText6: 'Хочу зарегистрироваться!',
//     loginText7: 'Регистрация',
//     loginText8: 'Повтори пароль',
//     loginText9: 'Перейти ко "Входу"',
//     loginText10: 'Восстановление (изменение) пароля',
//     loginText11: 'Зарегистрироваться',
//     loginText12: 'Восстановить',
//
//     formText1: 'Неправильный формат почты! Пример: example@mail.ru',
//     formText2: 'Пароль должен быть длиннее 6-ти символов!',
//     formText3: 'Пароли должны совпадать!',
//     formText4: 'Мы не нашли такого аккаунта',
//     formText5: 'Неверный пароль',
//     formText6: 'Ошибка, попробуй ещё раз позже :(',
//     formText7: 'Проверь все поля!',
//     formText8: 'Уже верифицирован, залогинься :)',
//     formText9: 'Нужно пройти верификацию (проверь почту)',
//     formText10: 'Послать письмо ещё раз',
//     formText11: 'Такой аккаунт уже существует',
//     formText12: 'Спасибо за регистрацию!',
//     formText13: 'Ты поможешь нам если ответишь на два небольших вопросика (можешь и пропустить), а мы сможем помочь тебе в будущем с выбором места для переезда, если это понадобится :)',
//     formText14: 'Твоя возрастная группа:',
//     formText15: 'Моложе 25 лет',
//     formText16: '25 - 40 лет',
//     formText17: '41 - 55 лет',
//     formText18: 'Старше 55 лет',
//     formText19: 'Примерный уровень доходов:',
//     formText20: 'Ниже среднего',
//     formText21: 'Средний',
//     formText22: 'Выше среднего',
//     formText23: 'Имя. Если пропустишь, в комментариях тебя будут видеть как "Аноним".',
//     formText24: 'Готово',
//     formText25: 'Проверь почту',
//     formText26: 'Один из этапов борьбы с накруткой - проверка соответствия зарегестрировавшегося и его почты. Поэтому мы отправили тебе письмо. Мы знаем что тебе не терпится, сразу после этого этапа сможешь начать. Проверяй почту :)',
//     formText27: 'Перейти ко "Входу"',
//     formText28: 'Изменение пароля',
//     formText29: 'Введи новый пароль',
//     formText30: 'Новый пароль совпадает со старым, введи другой',
//     formText31: 'Твоя ссылка для сброса пароля уже не действительна :(',
//     formText32: 'Получить новую',
//     formText33: 'Изменить пароль',
//     formText34: 'Мы отправили тебе на почту письмо. Перейдя по ссылке внутри, ты попадёшь на форму для изменения пароля. Только после введения нового пароля, предыдущий перестанет быть действительным.',
//     formText35: 'Понятно',
//     formText36: 'Нужно оценить все критерии!',
//     formText37: 'Где-то рядом уже есть твоя оценка',
//     formText38: 'Поделиться рейтингом',
//     formText39: 'Слишком часто оцениваешь, нужно подождать',
//     formText40: 'Слишком много попыток, погоди!',
//     formText41: 'Скопировано в буфер обмена',
//
//     caption1: `1 - ужасно, 5 - отлично`,
//     caption2: `1 - плохо, 5 - хорошо`,
//     caption3: `1 - ужас, 5 - супер`,
//     caption4: `1 - ужасно, 5 - круто`,
//     caption5: `1 - шумно, 5 - спокойно`,
//     caption6: `1 - грязно, 5 - чисто`,
//     caption7: `1 - далеко, 5 - рядом`,
//     caption8: `1 - тревожно, 5 - мирно`,
//     caption9: `1 - трудно, 5 - легко`,
//     caption10: `1 - тяжко, 5 - здорово`,
//     caption11: `1 - кошмар, 5 - класс`,
//
//     ratingPlaceholder: 'Чистоплотные и порядочные соседи, убирают за собаками...',
//     searchPlaceholder: 'Поиск...',
// }
